### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by aholland** [LambdaTest/homebrew-tap-lambdatest-tunnel#8]
Hi 

I get the following when trying to install LT using Homebrew.

Also, why doesn't LT turn up in a search on https://formulae.brew.sh/ ?

Thanks, Anthony
```
❰anthonyholland❙~/IdeaProjects/cyb❱✔≻ brew install lambdatest/tap-lambdatest-tunnel/lambdatest-tunnel
==> Tapping lambdatest/tap-lambdatest-tunnel
Cloning into '/opt/homebrew/Library/Taps/lambdatest/homebrew-tap-lambdatest-tunnel'...
remote: Enumerating objects: 110, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 110 (delta 30), reused 99 (delta 23), pack-reused 0
Receiving objects: 100% (110/110), 14.02 KiB | 1.56 MiB/s, done.
Resolving deltas: 100% (30/30), done.
Tapped 1 formula (16 files, 26.8KB).
==> Fetching lambdatest/tap-lambdatest-tunnel/lambdatest-tunnel
==> Downloading https://downloads.lambdatest.com/tunnel/v3/mac/64bit/LT_Mac.zip
###################################################################################################################################################### 100.0%
Error: lambdatest-tunnel: SHA256 mismatch
Expected: c4bac877bec641d94f9ef446b9496e7fe4720fb46b1a7880b877dafff9f5d6e2
  Actual: acdf4b11489452c6ab898fe1c92133a3ae923d8c8aa44fe910e978469c5c5714
    File: /Users/anthonyholland/Library/Caches/Homebrew/downloads/223cbe5022d51dfd6b47b2a675587e0319b7580b0562b6040ef7ff3243eb774e--LT_Mac.zip
To retry an incomplete download, remove the file above.
```

**Comment by pawan-lambda** [comment]
Hello Anthony,

We appreciate your concern that you've brought up. The reason it's not appearing in [homebrew-tap](https://formulae.brew.sh/) is that we're utilizing our own custom tap. However, we've addressed above problem of sha256 mismatch. Could you please give it another try on your end and verify?

Thank you.

**Comment by aholland** [comment]
I have tested the command and it is now working, thanks!

It's great to have this kind of response, where I suggested something through your support system and—whether it was already underway or in response to me—it's fully implemented and working a few months later. Go LambdaTest!

I run a `brew -upgrade` or `brew-upgrade --greedy` most mornings and I would argue it's a much better way to stay up to date than having to manage multiple custom auto-updaters and all of that sort of thing and suspect a lot of other developers would agree.

Regarding the custom tap, I've been looking into why one would maintain a custom tap, given that it makes your formula(s) much less easily discoverable. A quick Google search typically delivers a brew formula immediately, eg as shown below for Gimp.

<img width="958" alt="image" src="https://github.com/LambdaTest/homebrew-tap-lambdatest-tunnel/assets/1101312/a73153ba-5afc-4744-b048-521b3bc4db2a">


I understand the reasons may be Homebrew's _notability requirements_, including licensing requirements, open-source requirements and so on. Fair enough. But I would recommend then, if you're not already onto it, that you make it clear in your documentation that you do now have a Homebrew tap and formula for the tunnel software, and make the README a bit slicker.

In case you want to share it with others, I thought I'd share these instructions for setting up LamdaTest Tunnel as a service in IDEA on macOs with Homebrew. There are many variations that would work but this simple example definitely does, and will not need to change as version upgrades come in:

1. Install with Homebrew: `brew install lambdatest/tap-lambdatest-tunnel/lambdatest-tunnel`
2. Ignore the Cellar installation location information, and instead run `which lambdatest-tunnel`. The result should be something like `/opt/homebrew/bin/lambdatest-tunnel` depending on your version of macOS.
3. In IntelliJ add a new `Run/Debug Configuration` of type `Shell Script`. Select the `Script text` option.
4. Enter the following in the `Script text` field, where `{lambatest executable}` is the output of the `which` command in step 2, eg `/opt/homebrew/bin/lambdatest-tunnel`: 
`{lambatest executable} --user {user's login email} --key {user's access key} --tunnelName {user's tunnel name}`
5. Set working directory to the your project directory
6. In the Services tool window choose `Add (+ button) / Run Configuration Type / Shell Script
7. Your tunnel should now be listed as a service, eg:
![image](https://github.com/LambdaTest/homebrew-tap-lambdatest-tunnel/assets/1101312/f96ac7bc-fb07-41b8-b006-68fd791b496f)

**Comment by pawan-lambda** [comment]
Hello @aholland ,

**Comment by pawan-lambda** [comment]
Hello @aholland ,

My apologies for the delayed response. We're currently managing our custom tap as we didn't meet the open-source requirement of the source code in the Homebrew official tap. Your suggestion is appreciated, and I will take it into consideration and make necessary updates to the readme.

**Comment by pawan-lambda** [comment]
We have already made changes by cherry-picking some of your suggestions, we are focussing on a wide scale of user use cases, and some of these suggestions would narrow down the readme to IntelliJ users, hence keeping the issue closed.
