### ISSUE TITLE
README has errors

### ISSUE THREAD

**Issue by aholland** [LambdaTest/homebrew-tap-lambdatest-tunnel#9]
Looking at the attached/embedded image, the closing tag `</formula>` is showing and also the formula itself appears to be incorrect. When I attempt to install using this formula I get a message as follows:

```
❰anthonyholland❙~/IdeaProjects/cyb❱✘≻ brew install lambdatest/tap-lambdatest-tunnel
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=O#-   #     #                                                                                                                                             
==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: No available formula with the name "lambdatest/tap-lambdatest-tunnel". Did you mean lambdatest/tap-lambdatest-tunnel/lambdatest-tunnel?
```

<img width="892" alt="image" src="https://github.com/LambdaTest/homebrew-tap-lambdatest-tunnel/assets/1101312/722fbe82-47a1-4f37-84fe-ed27c0d219ae">

**Comment by pawan-lambda** [comment]
Hello @aholland ,

I apologize for the delay in my response. You can install it by running the following command: `brew install lambdatest/tap-lambdatest-tunnel/lambdatest-tunnel`. I have updated readme . 

<img width="794" alt="Screenshot 2023-09-01 at 11 22 49 AM" src="https://github.com/LambdaTest/homebrew-tap-lambdatest-tunnel/assets/113904056/bb6ebfc6-801a-41e5-a64e-adeb15dbaa7a">

**Comment by pawan-lambda** [comment]
This issue is resolved, and we are concluding this issue as we have updated the readme
